spring:
  profiles:
    active: dev
    include: secret

---
spring:
  config:
    activate:
      profile: dev
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    format_sql: true
    use_sql_comments: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
  logging:
    level:
      org.hibernate.SQL: debug
#  security:
#    oauth2:
#      client:
#        registration:
#          google:
#            client-id: YOUR_GOOGLE_CLIENT_ID
#            client-secret: YOUR_GOOGLE_CLIENT_SECRET
#            scope:
#              - email
#              - profile
#          naver:
#            client-id: YOUR_NAVER_CLIENT_ID
#            client-secret: YOUR_NAVER_CLIENT_SECRET
#            client-authentication-method: post
#            authorization-grant-type: authorization_code
#            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
#            scope:
#              - name
#              - email
#            client-name: Naver
#          kakao:
#            client-id: YOUR_KAKAO_CLIENT_ID
#            client-secret: YOUR_KAKAO_CLIENT_SECRET
#            client-authentication-method: post
#            authorization-grant-type: authorization_code
#            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
#            scope:
#              - profile_image
#              - account_email
#            client-name: Kakao
#          apple:
#            client-id: YOUR_APPLE_CLIENT_ID
#            client-secret: YOUR_APPLE_CLIENT_SECRET
#            client-authentication-method: post
#            authorization-grant-type: authorization_code
#            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
#            scope:
#              - name
#              - email
#            client-name: Apple
#        provider:
#          naver:
#            authorization-uri: https://nid.naver.com/oauth2.0/authorize
#            token-uri: https://nid.naver.com/oauth2.0/token
#            user-info-uri: https://openapi.naver.com/v1/nid/me
#            user-name-attribute: response
#          kakao:
#            authorization-uri: https://kauth.kakao.com/oauth/authorize
#            token-uri: https://kauth.kakao.com/oauth/token
#            user-info-uri: https://kapi.kakao.com/v2/user/me
#            user-name-attribute: id
#          apple:
#            authorization-uri: https://appleid.apple.com/auth/authorize
#            token-uri: https://appleid.apple.com/auth/token
#            user-info-uri: https://appleid.apple.com/auth/userinfo
#            jwk-set-uri: https://appleid.apple.com/auth/keys
#            user-name-attribute: sub
decorator:
  datasource:
    p6spy:
      enable-logging: true
      logging: slf4j
      multiline: true

aladin:
  api-key: YOUR_ALADIN_API_KEY
